<!-- picture -->
<!--
<table width="<?=IMAGE_WIDTH_SIZE+20?>" cellpadding="0" cellspacing="0">
  <tr>
    <td align="left" valign="top" class="prfTbCrnlt"><img src="/images/c_lt.gif"></td>
    <td class="prfedge" width="100%">&nbsp;</td>
    <td align="right" valign="top" class="prfTbCrnrt"><img src="/images/c_rt.gif"></td>
  </tr>
  <tr>
    <td colspan="3" class="prfsides" align="left"><span class="prfTbHdr">Picture</span> </td>
  </tr>
  <tr>
    <td colspan="3" class="prfsides" align="center" style="padding:5px;">
      <?=$PITURE_STRING?>
      <p class="prfName">
      <?=$names[0].' '.$names[1]?>
      </p> </td>
  </tr>
  <tr>
    <td align="left" valign="bottom" class="prfTbCrnlb"><img src="/images/c_lb.gif"></td>
    <td class="prfedgebt" width="100%">&nbsp;</td>
    <td align="right" valign="bottom" class="prfTbCrnrb"><img src="/images/c_rb.gif"></td>
  </tr>
</table>-->
<!-- picture -->
 <?=$PITURE_STRING?>
      <p class="prfName">
      <?=$names[0].' '.$names[1]?>
      </p> 
